# -*- coding: utf-8 -*-
"""Assignment-1: PYTHON BASICS & VARIABLES.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qtgavdj85sO7XgxnxPWwh8XsyAvDtoBH

##PYTHON BASICS & VARIABLES

1. Print Your Name
"""

print("Sathvika P")

"""2. Comments in Python"""

# This is a single-line comment

"""
This is a multi-line comment.
It can be used to write multiple lines of comments.
"""

print("Comments are used to explain the code and improve readability.")

"""3. Working with Basic Data Types"""

# Integer
num = 10

# Float
price = 99.99

# Boolean
is_student = True

# String (single character)
grade = "A"

print("Integer:", num, "Type:", type(num))
print("Float:", price, "Type:", type(price))
print("Boolean:", is_student, "Type:", type(is_student))
print("String:", grade, "Type:", type(grade))

"""4. Local vs Global Variables"""

# Global variable
name = "Global Variable"

def demo():
    global name

    # Local variable
    local_name = "Local Variable"

    print("Local Variable:", local_name)
    print("Global Variable:", name)

    # Modify global variable
    name = "Modified Global Variable"

demo()

print("Global Variable after function call:", name)

"""5. Type Checking & Dynamic Typing"""

x = 10
print("Value:", x)
print("Type:", type(x))

x = 25.5
print("Value:", x)
print("Type:", type(x))

x = True
print("Value:", x)
print("Type:", type(x))

x = "Python"
print("Value:", x)
print("Type:", type(x))

"""6. User Input Practice"""

name = input("Enter your name: ")
age = int(input("Enter your age: "))

print("Name:", name)
print("Age:", age)